#!/bin/bash
#PBS -l nodes=1:ppn=48
#PBS -l walltime=1:00:00


cd $PBS_O_WORKDIR 
module load   openmpi/4.0.3/gnu/9.3.0


KERT="0"
K="11"


for procs in 1 2 4 8 16 24; do
	for i in 1 2 3; do
	/usr/bin/time mpirun  --mca btl '^openib' -np ${procs} -x OMP_NUM_THREADS=2 blur.x  ${KERT} ${K} "./earth-large.pgm" > strong.${KERT}.${K}
	done 
done

KERT="0"
K="101"


for procs in 1 2 4 8 16 24; do
	for i in 1 2 3; do
	/usr/bin/time mpirun  --mca btl '^openib' -np ${procs} -x OMP_NUM_THREADS=2 blur.x  ${KERT} ${K} "./earth-large.pgm" > strong.${KERT}.${K}
	done 
done

KERT="1"
K="11"


for procs in 1 2 4 8 16 24; do
	for i in 1 2 3; do
	/usr/bin/time mpirun  --mca btl '^openib' -np ${procs} -x OMP_NUM_THREADS=2 blur.x  ${KERT} 0.2 ${K} "./earth-large.pgm" > strong.${KERT}.${K}
	done 
done

KERT="1"
K="101"


for procs in 1 2 4 8 16 24; do
	for i in 1 2 3; do
	/usr/bin/time mpirun  --mca btl '^openib' -np ${procs} -x OMP_NUM_THREADS=2 blur.x  ${KERT} 0.2 ${K} "./earth-large.pgm" > strong.${KERT}.${K}
	done 
done
